wrd = {
    "hello": "வணக்கம்",
    "world": "உலகம்",
    "good": "நலமாக",
    "morning": "காலை",
    "evening": "மாலை",
    "apple": "ஆப்பிள்",
    "book": "புத்தகம்",
    "computer": "கணினி",
    "water": "தண்ணீர்",
    "sun": "சூரியன்",
    "moon": "சந்திரன்",
    "flower": "மலர்",
    "tree": "மரம்",
    "cat": "பூனை",
    "dog": "நாய்",
    "fish": "மீன்",
    "bird": "பறவை",
    "house": "வீடு",
    "car": "கார்",
    "train": "ரயில்",
    "bus": "பேருந்து",
    "pen": "பேனல்",
    "pencil": "முழுவதும்",
    "school": "பள்ளி",
    "teacher": "ஆசிரியர்",
    "student": "மாணவன்",
    "friend": "நண்பர்",
    "food": "உணவு",
    "drink": "குடிப்பது",
    "sleep": "தூங்க",
    "wake": "எழுந்து",
    "happy": "மகிழ்ச்சி",
    "sad": "மனமில்லாத",
    "big": "பெரிய",
    "small": "சிறிய",
    "hot": "வெப்பநிலை",
    "cold": "குளிர்",
    "fast": "வேகமாக",
    "slow": "மெதுவாக",
    "new": "புதிய",
    "old": "பழைய",
    "beautiful": "அழகான",
    "ugly": "பெரிய",
    "happy": "மகிழ்ச்சி",
    "sad": "கனவு",
    "love": "காதல்",
    "hate": "வெறுக்கு",
    "goodbye": "வருகைப்படுகின்றேன்",
    "welcome": "வரவேற்பு",
    "please": "தயவுசெய்து",
    "thankyou": "நன்றி",
    "sorry": "மன்னிக்கவும்",
    "yes": "ஆம்",
    "no": "இல்லை",
    "today": "இன்று",
    "tomorrow": "நாளை",
    "yesterday": "நேற்று",
    "now": "இப்போது",
    "later": "பின்னர்",
    "always": "எப்போதும்",
    "never": "எதையும் இல்லை",
    "sometimes": "சில நேரங்களில்",
    "maybe": "சொல்ல முடியாது",
    "goodnight": "இனிய இரவு",
    "day": "நாள்",
    "night": "இரவு",
    "time": "நேரம்",
    "money": "பணம்",
    "work": "வேலை",
    "play": "விளையாடு",
    "study": "படித்தல்",
    "write": "எழுது",
    "read": "படிக்க",
    "speak": "பேசு",
    "listen": "கேட்டுக்கொள்",
    "watch": "பார்",
    "learn": "கற்றுக்கொள்",
    "understand": "புரிந்துகொள்",
    "forget": "மறக்க",
    "remember": "நினைத்துக்கொள்",
    "meet": "சந்திக்க",
    "see": "காண",
    "smile": "சிரிக்க",
    "cry": "அழு",
    "laugh": "சிரிக்க",
    "sing": "பாட",
    "dance": "ஆட",
    "jump": "ஆட்டு",
    "run": "ஓடு",
    "walk": "நட",
    "eat": "சாப்பிடு",
    "drink": "குடி",
    "cook": "சமை",
    "bath": "குளிய",
    "clean": "சுத்தம் செய்",
    "dirty": "கசிக்க",
    "open": "திற",
    "close": "மூடு",
    "hot": "வெப்பநிலை",
    "cold": "குளிர்",
    'Dog': 'நாய் (Nāy)',
    'Cat': 'பூனை (Pūṉai)',
    'Sun': 'சூரியன் (Sūriyan)',
    'Moon': 'சந்திரன் (Candiraṉ)',
    'Star': 'நட்சத்திரம் (Naṭcattiram)',
    'Sky': 'வானம் (Vāṉam)',
    'Book': 'புத்தகம் (Puttakam)',
    'Tree': 'மரம் (Maram)',
    'Rain': 'மழை (Maḻai)',
    'Fire': 'நெருக்கம் (Nerukkam)',
    'Bird': 'பறவை (Paṟavai)',
    'Fish': 'மீன் (Mīṉ)',
    'Ant': 'எறும்பு (Eṟumpu)',
    'Lion': 'சிங்கம் (Siṅkam)',
    'Rose': 'ரோஜா (Rōjā)',
    'Milk': 'பால் (Pāl)',
    'River': 'ஆறு (Āṟu)',
    'Leaf': 'இலை (Ilai)',
    'Frog': 'தவளை (Tavaḷai)',
    'Snake': 'பாம்பு (Pāmbu)',
    'Baby': 'குழந்தை (Kuḻantai)',
    'Earth': 'பூமி (Pūmi)',
    'Egg': 'முட்டாள் (Muṭṭāḷ)',
    'Tiger': 'புலி (Puli)',
    'Water': 'நீர் (Nīr)',
    'Wind': 'காற்று (Kāṟṟu)',
}
from nltk.corpus import words
import nltk
nltk.download('words')
words = words.words()
